//L298N MOTOR
#define RIGHT_IN1 22
#define RIGHT_IN2 28
#define LEFT_IN3 26
#define LEFT_IN4 24
#define RIGHT_PWM_ENA 3 //Must be PWM
#define LEFT_PWM_ENB 2  //Must be PWM

#define COMP_SPEED_R 0
#define COMP_SPEED_L 0

//HCSR04 RADAR
#define RADAR_REFRESH_RATE 10 //ms

#define HC_TRIGGER_RIGHT 32
#define HC_ECHO_RIGHT 30

#define HC_TRIGGER_CENTER 34
#define HC_ECHO_CENTER 36

#define HC_TRIGGER_LEFT 38
#define HC_ECHO_LEFT 40
